
spring:
# In-Memory cache
  cache:
    type: caffeine
    cache-names: interestRateCacheManager
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h,recordStats

#Logging
logging:
  level.root: INFO